Update issue templates
dysonltd/tmag5273 pull request #13
Opened 2024-11-29 11:27 UTC by ScottGibb

2024-11-29 14:13 UTC, petekubiak requested changes

2024-11-29 14:13 UTC, petekubiak commented on .github/ISSUE_TEMPLATE/bug_report.md
> +1. Installed vX.X.X
Presumably this means crate version? I'd be tempted to put this with the other version info

2024-11-29 14:13 UTC, petekubiak commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Bug fix (non-breaking change which fixes an issue)
If we're deleting the options which aren't relevant then these don't need to be tick boxes.

2024-11-29 14:13 UTC, petekubiak commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Bug fix (non-breaking change which fixes an issue)
Alternatively, change the instruction to something like "tick all that are relevant"

2024-11-29 14:13 UTC, petekubiak commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Hardware In the Loop Tests
Maybe remove these items and just leave the prompt to describe the tests

2024-11-29 14:13 UTC, petekubiak commented on CONTRIBUTING.md
> +# Contributing to  tmag5273
Two spaces here

2024-11-29 14:13 UTC, petekubiak commented on CONTRIBUTING.md
> +    git push origin your-feature-branch
This will result in an error as the branch will not exist on the remote.
I would either change the bit about creating a branch to give instructions on creating a branch within the GitHub UI, or alternatively change this to `git push --set-upstream origin your-feature-branch`, which will create the branch on the remote and then push

2024-11-29 16:03 UTC, petekubiak approved these changes

2024-12-05 16:13 UTC, petekubiak approved these changes

2024-12-05 16:13 UTC, petekubiak commented on .github/CODEOWNERS
Modern tools shouldn't get tripped up by this, but I'd suggest it would be best to avoid capitalisation in email addresses. I remember the time when a lot of things would fail if your email address was capitalised....

2024-12-05 16:45 UTC, jamessizeland approved these changes

2024-12-06 11:08 UTC, merged